version: '3.8'

services:
  api:
    image: ayazlogon/network-supplier-api:latest
    container_name: network_supplier_api
    restart: always
    ports:
      # Bind to 127.0.0.1:3056 so it is secure and only Nginx can proxy to it
      - "3056:3056"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
